from __future__ import annotations

import shlex
import subprocess
from pathlib import Path


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


def build(
    rendered_theme: Path,
    output_root: Path,
) -> tuple[Path, ...]:
    try:
        process = subprocess.run(
            [
                "vivid",
                "generate",
                str(rendered_theme),
            ],
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError as error:
        raise RuntimeError(
            "vivid is not installed or is not available in PATH"
        ) from error
    except subprocess.CalledProcessError as error:
        message = error.stderr.strip() or error.stdout.strip()

        raise RuntimeError(
            message or f"vivid exited with status {error.returncode}"
        ) from error

    ls_colors = process.stdout.strip()

    if not ls_colors:
        raise RuntimeError("vivid generated an empty LS_COLORS value")

    output = rendered_theme.parent / "ls-colors.zsh"

    write_atomic(
        output,
        (
            "# Generated by Base2Tone Tools from the active vivid theme.\n"
            f"export LS_COLORS={shlex.quote(ls_colors)}\n"
        ),
    )

    return (output.relative_to(output_root),)
